### ISSUE TITLE
Compile time bug in mpp/include/mpp_chksum_int.fh with LLVM Flang

### ISSUE THREAD

**Issue by mathomp4** [NOAA-GFDL/FMS#1738]
**Describe the bug**

First, I know LLVMFlang is not a supported compiler, see:

https://github.com/NOAA-GFDL/FMS/blob/fdd5d394354621385e02a179b8880e45be8896a6/CMakeLists.txt#L46-L49

but I thought I'd try anyway.

In trying to build FMS (2024.03, but file is same in `main`) with LLVM Clang/Flang (`main` as of yesterday), the compiler hit:
```
/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-8.14.0/src/FMS/mpp/include/mpp_chksum_int.fh:78:6: error: Dimension 1 of left-hand side has extent 2, but right-hand side has extent 1
       i4tmp = TRANSFER(mask_val , i4tmp )
       ^^^^^
/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-8.14.0/src/FMS/mpp/include/mpp_comm.inc:52:1: error: included here
  #include <mpp_chksum_int.fh>
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-8.14.0/src/FMS/mpp/mpp.F90:1371:1: error: included here
  #include <mpp_comm.inc>
  ^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**

Try to build FMS with LLVM Flang.

A small reproducer is:
```fortran
#ifdef FIX
   integer, allocatable :: i4tmp(:)
#else
   integer :: i4tmp(2)=0
#endif
   real :: mask_val
   i4tmp = TRANSFER(mask_val, i4tmp)
end
```

So without `-DFIX`:
```
> flang test.F90
error: Semantic errors in test.F90
./test.F90:7:4: error: Dimension 1 of left-hand side has extent 2, but right-hand side has extent 1
     i4tmp = TRANSFER(mask_val, i4tmp)
     ^^^^^
```
but with:
```
> flang -DFIX test.F90
>
```

Note: NAG Fortran (a notoriously strict Fortran compiler) returns a similar error:
```
> nagfor test.F90
NAG Fortran Compiler Release 7.2(Shin-Urayasu) Build 7228
Error: test.F90, line 7: Different vector lengths (2 and 1)
[NAG Fortran Compiler error termination, 1 error]
> nagfor -DFIX test.F90
NAG Fortran Compiler Release 7.2(Shin-Urayasu) Build 7228
[NAG Fortran Compiler normal termination]
```

The `-DFIX` code is per @tclune who said this is the right way to do it.

Thus, I'd think this code:

https://github.com/NOAA-GFDL/FMS/blob/fdd5d394354621385e02a179b8880e45be8896a6/mpp/include/mpp_chksum_int.fh#L56-L57

should become:

```fortran
  integer(KIND=i4_kind),allocatable::i4tmp(:)
  real(KIND=r4_kind),allocatable::r4tmp(:)
```

**Expected behavior**

The code to compile.

**System Environment**
Describe the system environment, include:
- OS: RHEL 8.10
- Compiler(s): flang 22.0.0git (built from `main` as of 2025-07-28)
- MPI: MPICH 4.3.1
- netCDF Version: C 4.9.2, Fortran 4.6.1
- Configure options: `-D32BIT=ON -D64BIT=ON -DFPIC=ON -DCONSTANTS=GEOS -DDEPRECATED_IO=ON`

(Yes, yes, I know. FMS1 IO. I have updates for our model in process to allow us to move to FMS 2025)

**Additional context**

**Comment by mathomp4** [comment]
This is odd. For reasons I'm not sure about, this now does work with Flang and FMS 2025.04. My only guess is that I now am forced to supply a `cmake/compiler_flags_LLVMFlang_Fortran.cmake` via `patch` and, well, no failure to build.

I guess I'll close this for now. I can re-open if necessary.
