### ISSUE TITLE
UFS S2S compilation error with 2020.04-alpha1 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#600]
**Describe the bug**
The UFS S2S model does not compile with 2020.04-alpha1 due to missing files in the SRCS_F90 list in fv3gfs/makefile 

**To Reproduce**
for example, 
git clone https://github.com/ufs-community/ufs-s2s-model.git
cd ufs-s2s-model/FMS && git checkout 2020.04-alpha1 
cd ../tests
./compile.sh $PWD../FV3 orion.intel 'CCPP=Y SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled MOM6=Y CICE6=Y CMEPS=Y' 1

**Expected behavior**
The model should compile without error 

**System Environment**
Describe the system environment, include:
- OS: Orion 
- Compiler(s): Intel 18.0.5
- MPI type: IMPI 18.0.5 
- netCDF Version: 4.7.4
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Compilation will succeed if the following is added to the SRCS_F90 list in fv3gfs/makefile  
 ../data_override/get_grid_version_fms2io.F90 
../data_override/get_grid_version_mpp.F90
